In [ ]:
import pandas as pd
import numpy as np


df = pd.DataFrame({
    "name": ["Yash", "Aman", "Vedant"],
    "age": [21,22, 13]
}, index= ["row1", "row2", "row3"])

df2 = pd.DataFrame(np.random.rand(3, 3), columns=["A", "B", "C"])

print(df)
print(df2)

data = np.random.rand(4, 2)
df3 = pd.DataFrame(data)

print(df3)

In [ ]:
import pandas as pd

df_productLookup = pd.read_csv('../data/AdventureWorks Product Lookup.csv')
df_productSubcategoriesLookup = pd.read_csv('../data/AdventureWorks Product Subcategories Lookup.csv')
# df_productLookup
# df_productSubcategoriesLookup
print("length of df is: ", len(df_productLookup))
print("Highest index of df is: ", max(df_productLookup))
print("Lowest index of df is: ", min(df_productLookup))
print("typeof df is: ", type(df_productLookup))
print("length of df is: ", len(df_productSubcategoriesLookup))
print("Highest index of df is: ", max(df_productSubcategoriesLookup))
print("Lowest index of df is: ", min(df_productSubcategoriesLookup))
print("typeof df is: ", type(df_productSubcategoriesLookup))

In [ ]:
df_trim = df_productLookup.filter(like='Product')
df_trim

In [ ]:

df_productLookup['New Column'] = 70   #the values 70 copies to the entire rows
df_productLookup

lang = np.random.randint(1, 100, size=293)
df_productLookup['New Column'] = lang   #this gives random whole numbers to the column 
df_productLookup

df_productLookup['Discount_Price'] = df_productLookup['ProductPrice'] * 0.85    #this creates a new column with 15% discount on product price
df_productLookup

In [ ]:
# import pandas as pd

# df_productLookup = pd.read_csv('../data/AdventureWorks Product Lookup.csv')
# df_productSubcategoriesLookup = pd.read_csv('../data/AdventureWorks Product Subcategories Lookup.csv')

df_productLookup[['ProductName', 'ProductCost']], df_productSubcategoriesLookup[['SubcategoryName']]        #this too works
df_productLookup.describe(), df_productLookup

In [25]:
import numpy as np
import pandas as pd
math_column = np.random.randint(1, 95, size= 145)
science_column = np.random.randint(1, 97, size= 145)
english_column = np.random.randint(1, 85, size= 145)
social_column = np.random.randint(1, 80, size= 145)
spanish_column = np.random.randint(1, 98, size= 145)
# students_column = 

df_marks = pd.DataFrame({'Math': math_column, 'Science': science_column, 'English': english_column, 'Social': social_column, 'Spanish': spanish_column})
df_marks

     Math  Science  English  Social  Spanish
0      92        9       68      10       27
1      56       31       75      72        5
2      24       93       69      43       11
3      10       36       57      39       72
4      62        6       13      33       86
..    ...      ...      ...     ...      ...
140    61       12        5      41       11
141    64       57       84      16       14
142    27       81       41      23        7
143    15       94       54       9       84
144    38       44       23      67       14

[145 rows x 5 columns]

### Table operations (Math)

In [ ]:
#In Coulumns
sum = df_marks[['Math', 'Science', 'Social', 'English', 'Spanish']].sum()
count = df_marks[['Math', 'Science', 'Social', 'English', 'Spanish']].count()
mean = df_marks[['Math', 'Science', 'Social', 'English', 'Spanish']].mean()
stdDeviation = df_marks[['Math', 'Science', 'Social', 'English', 'Spanish']].std()
max = df_marks[['Math', 'Science', 'Social', 'English', 'Spanish']].max()
min = df_marks[['Math', 'Science', 'Social', 'English', 'Spanish']].min()

dict = {'sum': sum, 'count': count, 'Mean': mean, 'Standard Deviation': stdDeviation, 'Max': max, 'Min': min}
dict

In [45]:
# In rows
df_marks['Total'] = df_marks['Math'] + df_marks['Science'] + df_marks['English'] + df_marks['Social'] + df_marks['Spanish']
df_marks['Average'] = (df_marks['Math'] + df_marks['Science'] + df_marks['English'] + df_marks['Social'] + df_marks['Spanish'])/5
df_marks['Percentage'] = (df_marks['Total'] / 500) * 100
df_marks

     Math  Science  English  Social  Spanish  Total  Average  Percentage
0      92        9       68      10       27    206     41.2        41.2
1      56       31       75      72        5    239     47.8        47.8
2      24       93       69      43       11    240     48.0        48.0
3      10       36       57      39       72    214     42.8        42.8
4      62        6       13      33       86    200     40.0        40.0
..    ...      ...      ...     ...      ...    ...      ...         ...
140    61       12        5      41       11    130     26.0        26.0
141    64       57       84      16       14    235     47.0        47.0
142    27       81       41      23        7    179     35.8        35.8
143    15       94       54       9       84    256     51.2        51.2
144    38       44       23      67       14    186     37.2        37.2

[145 rows x 8 columns]